(in-package :smartos-test)

(defun screen-hardware ()
  (multiple-value-bind (cols rows)
      (terminal-size)
    (terminal-clear)
    (draw-header cols)
    (format t "Hardware parameters~%~%")
    (format t "Collecting host information...~%~%")
    (finish-output)
    (let* ((report (gather-hardware-report))
           (text (hardware-report-text report)))
      (paginate-text text cols rows))))

(defun screen-vm-list ()
  (multiple-value-bind (cols rows)
      (terminal-size)
    (terminal-clear)
    (draw-header cols)
    (format t "Virtual machines~%~%")
    (format t "Command: ~{~A~^ ~}~%~%"
            +vmadm-list-cmd+)
    (finish-output)
    (let ((text (vm-list-table-text (list-vms))))
      (paginate-text text cols rows))))

(defun command-loop ()
  (handler-case
      (loop
         (terminal-clear)
         (multiple-value-bind (cols rows)
             (terminal-size)
           (draw-header cols)
           (format t "~%  1. Hardware parameters~%")
           (format t "  2. List virtual machines~%")
           (terpri)
           (format t "  0. Exit~%~%")
           (draw-status-line cols rows "0=Exit  Enter=choose"))
         (let ((choice (read-menu-choice :valid '("0" "1" "2"))))
           (cond
             ((string= choice "0") (return))
             ((string= choice "1") (screen-hardware))
             ((string= choice "2") (screen-vm-list)))))
    (error (e)
      (format t "~%Unexpected error: ~A~%" e)
      (wait-for-enter))))
